version: '3'
services:
  tmodloader:
    # image: 'jacobsmile/tmodloader1.4:latest'
    container_name: 'tmodloader'
    stdin_open: true
    tty: true
    ports:
      - "7777:7777"
    expose:
      - "7777"
    environment:
      # Download the Calamity mod and CalamityMusic mod.
      - "TMOD_AUTODOWNLOAD=${_TMOD_AUTODOWNLOAD}"
      # Enable the Calamity mod and CalamityMusic mod.
      - "TMOD_ENABLEDMODS=${_TMOD_ENABLEDMODS}"
      # Shutdown Message and Autosave Interval (In Minutes)
      - "TMOD_SHUTDOWN_MESSAGE=${_TMOD_SHUTDOWN_MESSAGE}"
      - "TMOD_AUTOSAVE_INTERVAL=${_TMOD_AUTOSAVE_INTERVAL}"
      # Server Settings
      - "TMOD_MOTD=${_TMOD_MOTD}"
      - "TMOD_PASS=${_TMOD_PASS}"
      - "TMOD_MAXPLAYERS=${_TMOD_MAXPLAYERS}"
      # The following world settings are only used when generating a new world.
      - "TMOD_WORLDNAME=${_TMOD_WORLDNAME}"
      - "TMOD_WORLDSEED=${_TMOD_WORLDSEED}"
      - "TMOD_DIFFICULTY=${_TMOD_DIFFICULTY}"
      # (Deprecated) If TMOD_USECONFIGFILE is set to "Yes", it is expected to have a serverconfig.txt mapped. The Server Settings above will be ignored.
      - "TMOD_USECONFIGFILE=No"
      - "UPDATE_NOTICE=false"

    volumes:
      - "tmodloader_data:/data"
      # Uncomment the below line if you plan to use a mapped config file. 
      # - "/path/to/config/config.txt:/root/terraria-server/serverconfig.txt"

# Define named volumes
volumes:
  tmodloader_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/tmodloader-data
